sudo: true
language: python

python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose

install:
  - pip install -r requirements.txt
  - pip install simab

script:
  - python tests/arms.py
  - python tests/algorithms.py

